apiVersion: v1
kind: Secret
metadata:
  name: aws-tokens
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc | quote }}
  AWS_SESSION_TOKEN: {{ .Values.aws.sessionToken | b64enc | quote }}