changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-release
    authors:
      - bot-user
  categories:
    - title: "🚨 Breaking Changes"
      labels:
        - breaking-change
    - title: "✨ New Features"
      labels:
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - bug
    - title: "⚙️ Maintenance & Refactoring"
      labels:
        - chore
        - refactor
    - title: "🚧 CI & Pipeline"
      labels:
        - ci
        - pipeline
    - title: "📝 Documentation Updates"
      labels:
        - documentation
    - title: "📦 Dependencies"
      labels:
        - dependencies
    - title: "🔀 Other Changes"
      labels:
        - "*"
