apiVersion: infraweave.io/v1
kind: S3Bucket
metadata:
  name: bucket2
spec:
  moduleVersion: 0.1.3-dev+test.10
  region: N/A
  variables:
    bucketName: "{{ S3Bucket::bucket1a::bucketName }}-after"
    tags:
      Name234: my-s3bucket
      Tjoho: "This is cool"
      Environment43: dev
      PreviousBucket: "{{ S3Bucket::bucket1a::bucketArn }}"
