FROM alpine:3.20 AS tofu
ARG TARGETARCH

ENV TOFU_VERSION=1.11.4

RUN apk add --no-cache wget unzip

# We rename tofu to terraform so that the runner doesn't need to know about vendor.
RUN wget https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_linux_${TARGETARCH}.zip && \
    unzip tofu_${TOFU_VERSION}_linux_${TARGETARCH}.zip && \
    mv tofu /usr/local/bin/terraform && \
    chmod +x /usr/local/bin/terraform