[package]
name = "cli"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

[dependencies]
clap = "3.0"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
colored = "2.0"
prettytable = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
anyhow = "1.0"
serde_yaml = "0.8"
log = "0.4"
ring = "0.17.8"
openssl = { version = "0.10", features = ["vendored"] }

env_common = { path = "../env_common" }
env_defs = { path = "../defs" }
env_utils = { path = "../utils" }
