apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: s3buckets.infrabridge.io
spec:
  group: infrabridge.io
  names:
    kind: S3Bucket
    listKind: S3BucketList
    plural: s3buckets
    singular: s3bucket
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bucketName:
                  type: string
                region:
                  type: string
                policy:
                  type: object
              required:
                - bucketName
                - region
            status:
              type: object
              properties:
                resourceStatus:
                  type: string
                lastStatusUpdate:
                  type: string
      additionalPrinterColumns:
      - name: ResourceStatus
        type: string
        jsonPath: .status.resourceStatus
        description: The current status of the S3 bucket
      - name: LastStatusUpdate
        type: string
        jsonPath: .status.lastStatusUpdate
        description: The time of the last status update
      - name: ResourceId
        type: string
        jsonPath: .metadata.annotations.deploymentId
        description: The unique identifier of the S3 bucket