apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "{{ plural }}.{{ group }}"
spec:
  group: "{{ group }}"
  names:
    kind: "{{ kind }}"
    listKind: "{{ listKind }}"
    plural: "{{ plural }}"
    singular: "{{ singular }}"
  scope: "Namespaced"
  versions:
    - name: "v1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: "object"
          properties:
            spec:
              type: "object"
              properties:
                bucketName:
                  type: "string"
                region:
                  type: "string"
                policy:
                  type: "object"
              required:
                - "bucketName"
                - "region"
            status:
              type: object
              properties:
                resourceStatus:
                  type: string
                lastStatusUpdate:
                  type: string
                logs:
                  type: string
      additionalPrinterColumns:
        - name: ResourceStatus
          type: string
          jsonPath: .status.resourceStatus
          description: The current status of the resource deployment
        - name: LastStatusUpdate
          type: string
          jsonPath: .status.lastStatusUpdate
          description: The time of the last status update
        - name: ResourceId
          type: string
          jsonPath: .metadata.annotations.deploymentId
          description: The unique identifier of the resource deployment
