apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "{{ plural }}.{{ group }}"
  annotations:
    infraweave.io/validating-webhook: "enabled"
spec:
  group: "{{ group }}"
  names:
    kind: "{{ kind }}"
    listKind: "{{ listKind }}"
    plural: "{{ plural }}"
    singular: "{{ singular }}"
  scope: "Namespaced"
  versions:
    - name: "v1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: "object"
          properties:
            spec:
              type: "object"
              properties:
                moduleVersion:
                  type: "string"
                stackVersion:
                  type: "string"
                region:
                  type: "string"
                reference:
                  type: "string"
                variables:
                  type: "object"
                  x-kubernetes-preserve-unknown-fields: true
                driftDetection:
                  type: "object"
                  properties:
                    enabled:
                      type: "boolean"
                    interval:
                      type: "string"
                    autoRemediate:
                      type: "boolean"
                    webhooks:
                      type: "array"
                      items:
                        type: "object"
                        properties:
                          url:
                            type: "string"
                          message:
                            type: "string"
              required:
                - "region"
                - "variables"
              oneOf:
                - required: ["moduleVersion"]
                - required: ["stackVersion"]
            status:
              type: object
              properties:
                resourceStatus:
                  type: string
                lastDeploymentEvent:
                  type: string
                lastCheck:
                  type: string
                logs:
                  type: string
                lastGeneration:
                  type: integer
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: ResourceStatus
          type: string
          jsonPath: .status.resourceStatus
          description: The current status of the resource deployment
        - name: LastDeploymentEvent
          type: string
          jsonPath: .status.lastDeploymentEvent
          description: The time of the last deployment event
        - name: LastCheck
          type: string
          jsonPath: .status.lastCheck
          description: The time of the last check of status update
        - name: ResourceId
          type: string
          jsonPath: .metadata.annotations.deploymentId
          description: The unique identifier of the resource deployment
