[build-system]
requires = ["maturin>=0.13"]
build-backend = "maturin"

[project]
name = "infraweave_py"
version = "0.1.0"
description = "Implement InfraWeave in Python"
readme = "README.md"
readme-content-type = "text/markdown"  # Explicitly specify Markdown
authors = [
    {name = "InfraWeave Team", email = "opensource@infraweave.com"}
]
dependencies = []
requires-python = ">=3.10"

[tool.setuptools]
packages = ["infraweave_py"]
