# crd_template.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "{{ plural }}.{{ group }}"
spec:
  group: "{{ group }}"
  names:
    kind: "{{ kind }}"
    listKind: "{{ listKind }}"
    plural: "{{ plural }}"
    singular: "{{ singular }}"
  scope: "Namespaced"
  versions:
    - name: "v1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: "object"
          properties:
            spec:
              type: "object"
              properties:
                bucketName:
                  type: "string"
                region:
                  type: "string"
                policy:
                  type: "object"
              required:
                - "bucketName"
                - "region"
