apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraweave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infraweave
  template:
    metadata:
      labels:
        app: infraweave
    spec:
      serviceAccountName: infraweave-service-account
      containers:
      - name: infraweave
        image: infraweave-operator:latest
        imagePullPolicy: Never
        env:
        - name: AWS_REGION
          value: {{ .Values.aws.region }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-tokens
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-tokens
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-tokens
              key: AWS_SESSION_TOKEN
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUST_LOG
          value: info
        - name: RUST_BACKTRACE
          value: "1"