apiVersion: v1
kind: ServiceAccount
metadata:
  name: infraweave-service-account
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infraweave-admission-controller-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infraweave-cluster-role
rules:
- apiGroups: ["infraweave.io", "apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infraweave-admission-controller-cluster-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infraweave-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: infraweave-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: infraweave-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infraweave-admission-controller-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: infraweave-admission-controller-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: infraweave-admission-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
