apiVersion: infraweave.io/v1
kind: S3Bucket
metadata:
  name: bucket2
spec:
  moduleVersion: 0.1.3-dev+test.10
  region: N/A
  variables:
    bucketName: "{{ Stack::variables::environment }}-bucket2"
