locals {
  tags = merge(var.tags, {
    # All INFRAWEAVE_* variables
    INFRAWEAVE_DEPLOYMENT_ID            = var.INFRAWEAVE_DEPLOYMENT_ID
    INFRAWEAVE_ENVIRONMENT              = var.INFRAWEAVE_ENVIRONMENT
    INFRAWEAVE_REFERENCE                = var.INFRAWEAVE_REFERENCE
    INFRAWEAVE_MODULE_VERSION           = var.INFRAWEAVE_MODULE_VERSION
    INFRAWEAVE_MODULE_TYPE              = var.INFRAWEAVE_MODULE_TYPE
    INFRAWEAVE_MODULE_TRACK             = var.INFRAWEAVE_MODULE_TRACK
    INFRAWEAVE_DRIFT_DETECTION          = var.INFRAWEAVE_DRIFT_DETECTION
    INFRAWEAVE_DRIFT_DETECTION_INTERVAL = var.INFRAWEAVE_DRIFT_DETECTION_INTERVAL
    # INFRAWEAVE_GIT_* is only applied when pushing to a GitHub repository
    INFRAWEAVE_GIT_COMMITTER_EMAIL      = var.INFRAWEAVE_GIT_COMMITTER_EMAIL
    INFRAWEAVE_GIT_COMMITTER_NAME       = var.INFRAWEAVE_GIT_COMMITTER_NAME
    INFRAWEAVE_GIT_ACTOR_USERNAME       = var.INFRAWEAVE_GIT_ACTOR_USERNAME
    INFRAWEAVE_GIT_ACTOR_PROFILE_URL    = var.INFRAWEAVE_GIT_ACTOR_PROFILE_URL
    INFRAWEAVE_GIT_REPOSITORY_NAME      = var.INFRAWEAVE_GIT_REPOSITORY_NAME
    INFRAWEAVE_GIT_REPOSITORY_PATH      = var.INFRAWEAVE_GIT_REPOSITORY_PATH
    INFRAWEAVE_GIT_COMMIT_SHA           = var.INFRAWEAVE_GIT_COMMIT_SHA
  })
}