[package]
name = "env_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5"
walkdir = "2.3"
hcl-rs = "0.16.9"
serde_json = "1.0"
env_defs = { path = "../defs" }
