apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modules.infrabridge.io
spec:
  group: infrabridge.io
  names:
    kind: Module
    listKind: ModuleList
    plural: modules
    singular: module
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            spec:
              type: object
              properties:
                provider:
                  type: string
                source:
                  type: object
                  properties:
                    type:
                      type: string
                    S3:
                      type: object
                      properties:
                        bucket:
                          type: string
                        path:
                          type: string
                    git:
                      type: object
                      properties:
                        url:
                          type: string
                        ref:
                          type: string
                moduleName:
                  type: string
                version:
                  type: string
                environment:
                  type: string
                parameters:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                outputs:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      type:
                        type: string
      additionalPrinterColumns:
      - name: ModuleVersion
        type: string
        jsonPath: .spec.version
        description: The current status of the S3 bucket
      # - name: LastStatusUpdate
      #   type: string
      #   jsonPath: .status.lastStatusUpdate
      #   description: The time of the last status update
