apiVersion: infrabridge.io/v1
kind: Module
metadata:
  # group: infrabridge.io    # The group of the module
  name: iam-eks-role # The name of the module you define
spec:
  moduleName: IamEksRole # metadata.name cannot have any uppercase, which is why we need this
  version: 0.0.2 # The released version to use
  description: |
    # iam-eks-role

    Creates an IAM role that can be assumed by one or more EKS `ServiceAccount` in one or more EKS clusters. Unlike [iam-assumable-role-with-oidc](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-assumable-role-with-oidc/), this module:

    - Does not require any knowledge of cluster OIDC information as `data` resources are used
    - Supports assuming the role from multiple EKS clusters, for example used in DR or when a workload is spread across clusters
    - Support multiple `ServiceAccount` in the same cluster, for example when a workload runs in multiple namespaces
    - More suitable for non-cluster admins as implementation is simpler
    - More suitable for when the IAM role and cluster resources are in separate Terraform configurations
    - Does not support multiple regions, consider using [iam-role-for-service-accounts-eks](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-role-for-service-accounts-eks/) if role needs to support clusters in multiple regions

    This module is for use with AWS EKS. For details of how a `ServiceAccount` in EKS can assume an IAM role, see the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

    Implementation notes:

    - The EKS cluster needs to exist first, in the current AWS account and region
    - The key in the `cluster_service_accounts` is the exact name of the EKS cluster
