apiVersion: infraweave.io/v1
kind: Stack
metadata:
  name: bucketcollectionlifecycle
spec:
  stackName: BucketCollectionLifecycle
  reference: https://github.com/infraweave-io/stacks/bucketcollection-lifecycle
  description: |
    This is a deployment stack consisting of two S3-buckets demonstrating stack-level variables.
    
    ## Details
    Both buckets use a stack-level variable 'environment' to construct their names.
    This allows setting a single value that's used across multiple modules in the stack.

  stackVariableDefinitions:
    - name: enableTwoBuckets
      description: Only use one bucket
      type: "bool"

  lifecycles:
    enabled:
      bucket2: "{{ Stack::variables::enableTwoBuckets }}"

  examples:
    - name: bucketcollection-lifecycle-example
      description: |
        # Stack variables example

        This demonstrates using stack-level variables across multiple modules.
        The 'environment' variable is set once at the stack level and used by both buckets.
      variables:
        stack:
          enableTwoBuckets: false
