FROM python:3.12-slim

WORKDIR /var/task

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

ENV TZ="UTC"

COPY handler_dev.py ./
COPY source/ ./source/

CMD ["python", "handler_dev.py"]
