FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

ENV TZ="UTC"

COPY handler_aws.py ./
COPY source/ ./source/

CMD ["handler_aws.handler"]
