name: CI/CD

on:
  workflow_call:
    secrets: {}
    inputs:
      release:
        description: "Whether this is a release build"
        required: false
        type: boolean
        default: false
      pre_release:
        description: "Whether this is a pre-release build"
        required: false
        type: boolean
        default: false
      release_branch:
        description: "Branch to treat as the release branch (e.g. main, master)"
        required: true
        type: string
    outputs:
      version:
        description: "Calculated version from calculate-version job"
        value: ${{ jobs.calculate-version.outputs.version }}
      base_tag:
        description: "Base tag from calculate-version job"
        value: ${{ jobs.calculate-version.outputs.base_tag }}
  workflow_dispatch:
    inputs:
      release:
        description: "Whether this is a release build"
        required: false
        type: boolean
        default: false
      pre_release:
        description: "Whether this is a pre-release build"
        required: false
        type: boolean
        default: false
      release_branch:
        description: "Branch to treat as the release branch (e.g. main, master)"
        required: false
        type: string
        default: "main"

jobs:
  calculate-version:
    permissions:
      contents: read
    uses: ./.github/workflows/calculate-version.yml
    with:
      release: ${{ inputs.release || false }}
      pre_release: ${{ inputs.pre_release || false }}
      release_branch: ${{ inputs.release_branch }}

  build:
    needs: calculate-version
    permissions:
      contents: read
    uses: ./.github/workflows/binaries.yml
    with:
      version: ${{ needs.calculate-version.outputs.version }}

  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  docker:
    needs: [calculate-version, build, test]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker.yml
    with:
      version: ${{ needs.calculate-version.outputs.version }}
      push: >-
        ${{
          ((inputs.release || inputs.pre_release)
            && github.ref == format('refs/heads/{0}', inputs.release_branch))
          || (github.event_name == 'pull_request'
            && vars.PUSH_PR_IMAGE == 'true')
        }}

  wheels:
    needs: [calculate-version]
    permissions:
      contents: read
    uses: ./.github/workflows/wheels-maturin-action.yml
    with:
      version: ${{ needs.calculate-version.outputs.version }}
