name: Build and Release Binaries for CLI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  PROJECT_NAME: cli
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-arm64
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
          - name: windows-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@fcf085fcb4b4b8f63f96906cd713eb52181b5ea4
        with:
          targets: "${{ matrix.target }}"

      - name: Setup Cache for Cargo
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6

      - name: Install Cross-Compilation Dependencies
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build Binary
        run: cargo build -p ${PROJECT_NAME} --verbose --locked --release --target ${{ matrix.target }}

      - name: Prepare Binary for Release
        shell: bash
        run: |
          BIN_SUFFIX=""
          if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
            BIN_SUFFIX=".exe"
          fi

          BIN_OUTPUT="target/${{ matrix.target }}/release/${PROJECT_NAME}${BIN_SUFFIX}"
          BIN_RELEASE="cli-${{ matrix.name }}${BIN_SUFFIX}"

          mkdir -p "./cli-releases"

          if [[ -f "$BIN_OUTPUT" ]]; then
            mv "$BIN_OUTPUT" "./cli-releases/$BIN_RELEASE"
          else
            echo "Error: Built binary not found at $BIN_OUTPUT" && exit 1
          fi

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.name }}
          path: ./cli-releases/cli-${{ matrix.name }}*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./cli-releases

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: ./cli-releases/** # Upload all binaries as release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
