name: Build Kubernetes Operator Docker Image

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-and-push-docker-template.yml
    with:
      version: ${{ github.ref_name }}
      image_name: operator
      folder: operator
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}