name: Build Docker CLI image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g. v1.0.0)'
        required: true

jobs:
  build-and-push-image1:
    uses: ./.github/workflows/build-and-push-docker-template.yml
    with:
      version: ${{ github.event.inputs.version }}
      image_name: cli
      folder: cli
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}