name: Build AWS GitOps Docker Image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push-image1:
    uses: ./.github/workflows/build-and-push-docker-template.yml
    with:
      version: ${{ github.ref_name }}
      image_name: gitops-aws
      folder: gitops
      dockerfile: Dockerfile.lambda
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}