name: Build Python Wheels

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            python-arch: x64
        #   - os: ubuntu-latest
        #     arch: arm64
        #   - os: macos-latest
        #     arch: x86_64
        #   - os: macos-latest
        #     arch: arm64
        #   - os: windows-latest
        #     arch: x86_64  # Only x86_64 is supported for Windows

        # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.12.7"] # See versions here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-arch }}

      - name: Install Rust
        run: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin>=0.13 cibuildwheel

      - name: Check Maturin Version
        run: maturin --version


      - name: Copy dependencies
        run: |
          ls -la
          cp -r env_common infraweave_py/env_common
          cp -r defs infraweave_py/defs
          cp -r utils infraweave_py/utils
          cp -r env_aws infraweave_py/env_aws
          cp -r env_azure infraweave_py/env_azure

      - name: Adjust Cargo.toml paths
        working-directory: infraweave_py
        run: |
          sed -i 's#path = "../env_common"#path = "env_common"#' Cargo.toml
          sed -i 's#path = "../defs"#path = "defs"#' Cargo.toml
          sed -i 's#path = "../utils"#path = "utils"#' Cargo.toml
  
      - name: Build Wheels
        working-directory: infraweave_py
        env:
          CIBW_BUILD: "cp311-manylinux_x86_64"
          # CIBW_BUILD: "cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64"
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BEFORE_BUILD_LINUX: |
            yum install -y perl-core
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
          CIBW_ENVIRONMENT: |
            PATH=$HOME/.cargo/bin:$PATH
            RUSTFLAGS=""
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"
        run: |
            cibuildwheel --output-dir dist
        
  
      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
            name: ${{ runner.os }}-${{ matrix.arch }}-wheels
            path: infraweave_py/dist/*.whl
