name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-

      - name: Build with warnings as errors
        run: cargo build --all-targets
        env:
          RUSTFLAGS: "-D warnings"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-lint-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-lint-target-
            ${{ runner.os }}-cargo-build-target-

      - name: Run cargo fmt
        run: cargo fmt

      - name: Run cargo clippy
        run: cargo clippy

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-test-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-target-
            ${{ runner.os }}-cargo-build-target-

      - name: Run unit tests
        run: make unit-tests

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [aws,azure]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-integration-${{ matrix.provider }}-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-integration-${{ matrix.provider }}-target-
            ${{ runner.os }}-cargo-build-target-

      - name: Run integration tests for ${{ matrix.provider }}
        run: |
          make ${{ matrix.provider }}-integration-tests

  docker-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: cli
            dockerfile: cli/Dockerfile
          - package: gitops
            dockerfile: gitops/Dockerfile.lambda
          - package: reconciler
            dockerfile: reconciler/Dockerfile.lambda
          - package: terraform_runner
            dockerfile: terraform_runner/Dockerfile.terraform
          - package: terraform_runner
            dockerfile: terraform_runner/Dockerfile.tofu
          - package: webserver-openapi
            dockerfile: webserver-openapi/Dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ${{ matrix.package }} package using ${{ matrix.dockerfile }}
        run: docker build -f ${{ matrix.dockerfile }} .

  python-builds:
    name: Build python ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux-x86_64
            os: ubuntu-latest
            arch: x86_64
            python-arch: x64
            cibw-build: cp311-manylinux_x86_64
          - name: macos-arm64
            os: macos-latest
            arch: arm64
            python-arch: arm64
            cibw-build: cp311-macosx_arm64
          # - name: linux-aarch64
          #   os: ubuntu-latest
          #   arch: aarch64
          #   python-arch: arm64
          #   cibw-build: cp311-manylinux_aarch64
          # - os: macos-latest
          #   arch: x86_64
          #   python-arch: x64
          # - os: ubuntu-latest
          #   arch: arm64
          #   python-arch: arm64
          # - os: macos-latest
          #   arch: x86_64
          #   python-arch: x64
          #   - os: windows-latest
          #     arch: x86_64  # Only x86_64 is supported for Windows
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          architecture: ${{ matrix.python-arch }}

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin==1.7.5 cibuildwheel

      - name: Check Maturin Version
        run: maturin --version

      - name: Prepare Dependencies for dockerized build
        if: runner.os == 'Linux'
        run: |
          cp -r env_common infraweave_py/env_common
          cp -r defs infraweave_py/defs
          cp -r utils infraweave_py/utils
          cp -r env_aws infraweave_py/env_aws
          cp -r env_azure infraweave_py/env_azure

      - name: Adjust Cargo.toml paths for dockerized build
        if: runner.os == 'Linux'
        working-directory: infraweave_py
        run: |
          sed -i 's#path = "../env_common"#path = "env_common"#' Cargo.toml
          sed -i 's#path = "../defs"#path = "defs"#' Cargo.toml
          sed -i 's#path = "../utils"#path = "utils"#' Cargo.toml

      - name: Build Wheels
        working-directory: infraweave_py
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.cibw-build }}
          CIBW_ENVIRONMENT: |
            PATH=$HOME/.cargo/bin:$PATH
            RUSTFLAGS=""
          CIBW_BEFORE_BUILD_LINUX: |
            yum install -y perl-core
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
          CIBW_BEFORE_BUILD_MACOS: |
            brew install openssl
        run: |
          cibuildwheel --output-dir dist
      